export default {
  "login": "ericmahare",
  "id": 98595024,
  "node_id": "U_kgDOBeBw0A",
  "avatar_url": "https://avatars.githubusercontent.com/u/98595024?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/ericmahare",
  "html_url": "https://github.com/ericmahare",
  "followers_url": "https://api.github.com/users/ericmahare/followers",
  "following_url": "https://api.github.com/users/ericmahare/following{/other_user}",
  "gists_url": "https://api.github.com/users/ericmahare/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/ericmahare/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/ericmahare/subscriptions",
  "organizations_url": "https://api.github.com/users/ericmahare/orgs",
  "repos_url": "https://api.github.com/users/ericmahare/repos",
  "events_url": "https://api.github.com/users/ericmahare/events{/privacy}",
  "received_events_url": "https://api.github.com/users/ericmahare/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Eric Mahare",
  "company": null,
  "blog": "https://erikmahare-portfolio.netlify.app/",
  "location": "Nairobi, Kenya",
  "email": null,
  "hireable": null,
  "bio": "Full-stack web developer: React, Ruby on rails | Love to play scrabble during my free time | Currently open to new opportunities.",
  "twitter_username": "erikmahare",
  "public_repos": 50,
  "public_gists": 0,
  "followers": 84,
  "following": 71,
  "created_at": "2022-01-28T13:04:04Z",
  "updated_at": "2022-11-14T20:07:20Z"
  }